package quests

// Automatically generated by ./utils/generate_enemy_weapon_types.py
// Do not manually modify!

type EnemyType int

const (
	asteroid EnemyType = iota
	baf
	bafBlue
	bafRed
	crowder
	inertiac
	kamikaze
	mothership
	mothershipSuper
	rollingCube
	rollingSphere
	spiny
	ufo
	wary
)

var EnemyTypeStrings = map[EnemyType]string{
	asteroid:        "ASTEROID",
	baf:             "BAF",
	bafBlue:         "BAF_BLUE",
	bafRed:          "BAF_RED",
	crowder:         "CROWDER",
	inertiac:        "INERTIAC",
	kamikaze:        "KAMIKAZE",
	mothership:      "MOTHERSHIP",
	mothershipSuper: "MOTHERSHIP_SUPER",
	rollingCube:     "ROLLING_CUBE",
	rollingSphere:   "ROLLING_SPHERE",
	spiny:           "SPINY",
	ufo:             "UFO",
	wary:            "WARY",
}
