package quests

// Automatically generated by ./utils/generate_enemy_weapon_types.py
// Do not manually modify!

type WeaponType int

const (
	atomizeExplosion WeaponType = iota
	bullet
	freezeExplosion
	mace
	plasmaField
	repulsiveExplosion
	wallTrailLasso
)
